### Get Carts
GET {{ host }}/branches/{{ branch }}/carts
Accept: application/json
Authorization: Bearer {{ accessToken }}

### Store Cart

POST {{ host }}/branches/{{ branch }}/carts
Accept: application/json
Authorization: Bearer {{ accessToken }}
Content-Type: application/json

{
    "sku_uuid": "9c3d2acf-dd1f-4d90-be1d-a94dc89f6c04",
    "quantity": 2
}

### Empty Cart

DELETE {{ host }}/branches/{{ branch }}/carts/empty
Accept: application/json
Authorization: Bearer {{ accessToken }}
